### ISSUE TITLE
Unable to extract native library from a nested JAR

### ISSUE THREAD

**Issue by hildo** [fizzed/jne#9]
I am writing a Spring Boot application, which has a nested dependency on cedar-java-uber.jar.  So, the JAR file created for my Spring application has the cedar-java-uber jar at /BOOT-INF/lib
![image](https://github.com/user-attachments/assets/46dbf05f-ceb5-4baa-b9c0-11b193215b8d)

cedar-java-uber.jar has native libraries in it, and it using fizzed JNE to extract it in order to load the library.  In this case, my application is looking for the native library in the Cedar JAR file at /jne/linux/x86_64/libcedar_java_ffi.so
![image](https://github.com/user-attachments/assets/8cbd94dd-7c86-4a3e-ba5d-452da52e6471)

However, the extraction process fails.  After enabling trace logging, it looks like the correct native library is being found, it's just the extraction process doesn't handle the nexted JAR

```
00:23:34.052 [main] DEBUG com.fizzed.jne.PlatformInfo -- Detected LINUX abi GNU (in 2 ms)
00:23:34.055 [main] TRACE com.fizzed.jne.JNE -- Finding fileName [libcedar_java_ffi.so] targetFileName [libcedar_java_ffi.so] os [LINUX] arch [X64] abi [GNU]...
00:23:34.055 [main] TRACE com.fizzed.jne.JNE -- Finding resource [/jne/linux/x64/libcedar_java_ffi.so]
00:23:34.056 [main] TRACE com.fizzed.jne.JNE -- Finding resource [/jne/linux/x86_64/libcedar_java_ffi.so]
00:23:34.057 [main] TRACE com.fizzed.jne.JNE -- Resource found @ jar:nested:/backend.jar/!BOOT-INF/lib/cedar-java-4.2.2-uber.jar!/jne/linux/x86_64/libcedar_java_ffi.so
00:23:34.057 [main] TRACE com.fizzed.jne.JNE -- Resource in jar; extracting file if necessary...
00:23:34.058 [main] DEBUG com.fizzed.jne.JNE -- Exception while finding library: URI scheme is not "file"

```

Is this something that can be supported?  The auto-extraction is very handy

**Comment by jjlauer** [comment]
Interesting, I don't believe I've ever come across nested jars in any my years of Java, but happy to accept your PR.

**Comment by jjlauer** [comment]
Version 4.3.0 just released with your PR. Should it maven central in next hour or so.

**Comment by hildo** [comment]
Thank you!  I had never come across it before as well.  Thank you for providing helpful trace logging which helped me learn about this.
